### ISSUE TITLE
AutoHidden Unit Watch Panels does not appear in "unlocked" mode

### ISSUE THREAD

**Issue by BannZay** [kurapica/AshToAsh#4]
Steps to reproduce:
1. Login
2. write '/ata unlock'
3. Right click on panel -> Add Panel -> Unit Watch Panel
4. Right click on newly created unit watch panel -> Auto Hide -> Add Macro Condition -> Select "nodead" (or any other true condition like 'noraid')

Expected: panel is visible in unlocked mode
Actual: panel disappeared, you can no longer access that panel settings, nor delete panel or its parent.

Wotlk Classic, Ata r039

**Comment by BannZay** [comment]
https://github.com/kurapica/AshToAsh/blob/61f754d74fbb5619a8a917a05866f0192a2f1e01/Template.lua#L26
Issue is gone if AshUnitWatchPanel inherit Scorpio.Secure.SecureGroupPanel, but I have no idea what else could be broken this way xD

**Comment by kurapica** [comment]
That's because the SecureGroupPanel don't auto hide itself, instead of that it apply the auto hide feature on its shadow group header, when shadow group header hidden, all unit will be cleared, the secure group panel will also clear its units but still remain visible.

I don't really used the auto hide feature on unit watch panel, so this is a common bug, I fixed that in r040 with a tiny fix, could improve it in a later versions.

**Comment by BannZay** [comment]
Thank you
